sdg_homepage:
    path:     /
    defaults: { _controller: SDGBundle:Default:index }

sdg_login:
    path:     /signin
    defaults: { _controller: SDGBundle:Default:login }

sdg_sgnin:
    path:     /log
    defaults: { _controller: SDGBundle:Default:signin }