sdg_homepage:
    path:     /
    defaults: { _controller: SDGBundle:Default:index }

sdg_login:
    path:     /signin
    defaults: { _controller: SDGBundle:Default:login }

sdg_sgnin:
    path:     /log
    defaults: { _controller: SDGBundle:Default:signin }

sdg_register:
    path:     /signup
    defaults: { _controller: SDGBundle:Default:register }

sdg_medecin:
    path:     /medecin
    defaults: { _controller: SDGBundle:Default:medecin }
ajout_article:
    path:     /ajoutarticle
    defaults: { _controller: SDGBundle:Article:ajout }