sdg_homepage:
    path:     /
    defaults: { _controller: SDGBundle:Default:index }

sdg_medecin:
    path:     /medecin
    defaults: { _controller: SDGBundle:Default:medecin }

sdg_association:
    path:     /assoc
    defaults: { _controller: SDGBundle:Default:association }

sdg_newevent:
    path:     /newevent
    defaults: { _controller: SDGBundle:Evenement:new }

ajout_article:
    path:     /ajoutarticle
    defaults: { _controller: SDGBundle:Article:ajout }

sdg_allevents:
    path:     /allevent
    defaults: { _controller : SDGBundle:Evenement:all }


list_article:
    path:     /listarticle/{specialite}
    defaults: { _controller: SDGBundle:Article:list }
detail_article:
    path:     /detailarticle/{id}
    defaults: { _controller: SDGBundle:Article:detail }

list_medecin:
    path:     /listmedecin
    defaults: { _controller: SDGBundle:User:list }

sdg_postsos:
    path:     /newsos
    defaults: { _controller: SDGBundle:Evenement:newsos }